identifier              = "my-db2-instance"
aws_region              = "us-east-2"
instance_class          = "db.t3.medium"
allocated_storage       = 100
storage_type            = "gp3"
db_name                 = "RDSDB2"
db_engine               = "db2-se"
db_engine_version       = "11.5"
major_engine_version    = "11.5"
family                  = "db2-se-11.5"
license_model           = "bring-your-own-license"
time_zone               = "US/Eastern"
max_allocated_storage   = 500
iops                    = 3000
tcp_port                = 50400
ssl_port                = 50409
ibm_customer_id         = "0186142"
ibm_site_id             = "4175004"
db_username             = "db2inst1"
subnet_ids              = ["subnet-1525176f", "subnet-ea77eda6"]
vpc_id                  = "vpc-4f64b924"
vpc_cidr                = "172.31.0.0/16"
multi_az                = false
enhanced_monitoring_enabled = true
s3_bucket_name          = "example-rds-db2-s3-access"
alert_email_address     = "abc@example.com"
maintenance_window      = "Tue:04:00-Tue:04:30"
backup_window           = "19:00-23:00"
backup_retention        = 7

tags = {
  Environment = "Test"
  Project     = "DB2Deployment"
}
